# AAH Backend Dockerfile
FROM python:3.12-slim
WORKDIR /app
COPY . /app
RUN pip install --upgrade pip && pip install poetry && poetry install --no-root
CMD ["uvicorn", "aah_api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
