"""Agent chat — per-delegate embedded chat sessions.

Each session is scoped to a delegate. The assistant reply is generated by the
cheap-tier LLM with context drawn from (1) the delegate's identity, (2) the
user's career goals, (3) a small window of recent memories, and (4) the last
~20 turns of conversation history. Budget enforcement is delegate-scoped.
"""

import logging
import uuid
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from memory.graph import (
    create_chat_session,
    list_chat_sessions,
    list_chat_messages,
    add_chat_message,
    list_memories,
    get_career_goals,
)
from skills.llm_client import chat as llm_chat, BudgetExceededError

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/v1/chat", tags=["chat"])

MAX_HISTORY_TURNS = 20
MAX_MEMORY_ITEMS = 8


DELEGATE_PERSONAS: dict[str, str] = {
    "recruiter": (
        "You are the Recruiter delegate — you help the user evaluate job "
        "opportunities, understand recruiter outreach, and calibrate their "
        "dealbreakers. You reference opportunity scores and policy rules when "
        "relevant. You're direct and pragmatic."
    ),
    "calendar": (
        "You are the Calendar delegate — you help the user manage their time, "
        "find slots, and coordinate interviews. You're succinct and "
        "time-zone aware."
    ),
    "comms": (
        "You are the Comms delegate — you help triage messages across channels, "
        "draft replies, and flag urgent items. You're crisp and context-aware."
    ),
    "finance": (
        "You are the Finance delegate — you track spending, detect recurring "
        "charges, and flag anomalies. You're precise with numbers and never "
        "give investment advice."
    ),
    "shopping": (
        "You are the Shopping delegate — you watch prices and alert on deals. "
        "You never recommend a purchase without the user's explicit approval."
    ),
    "learning": (
        "You are the Learning delegate — you detect skill gaps against the "
        "user's career goals and suggest focused learning paths."
    ),
    "health": (
        "You are the Health delegate — you track routines, streaks, and "
        "appointments. You never give medical advice."
    ),
}


def _system_prompt(delegate_id: str, memories: list[dict], goals) -> str:
    persona = DELEGATE_PERSONAS.get(
        delegate_id,
        f"You are the {delegate_id} delegate inside the Cadbury Personal Assistant.",
    )
    parts = [
        persona,
        "\n# Operating rules",
        "- Keep replies concise (1–3 short paragraphs or a tight bullet list).",
        "- Never claim to have taken an action unless the user explicitly asks you to run a pipeline or approve something.",
        "- If you don't know, say so and suggest what the user could check.",
        "- Reference the user's goals and memories naturally — do not recite them as a list.",
    ]

    if goals is not None:
        goal_data = getattr(goals, "model_dump", lambda: {})()
        if goal_data:
            roles = goal_data.get("target_roles") or []
            comp = goal_data.get("target_compensation") or {}
            locations = goal_data.get("target_locations") or []
            dealbreakers = goal_data.get("dealbreakers") or []
            parts.append("\n# User's career goals")
            if roles:
                parts.append(f"- Target roles: {', '.join(roles[:5])}")
            if comp:
                parts.append(f"- Compensation: {comp}")
            if locations:
                parts.append(f"- Locations: {', '.join(locations[:5])}")
            if dealbreakers:
                parts.append(f"- Dealbreakers: {', '.join(dealbreakers[:8])}")

    if memories:
        parts.append("\n# Recent memories")
        for m in memories[:MAX_MEMORY_ITEMS]:
            parts.append(f"- [{m.get('category', 'note')}] {m.get('content', '')}")

    return "\n".join(parts)


class ChatMessageIn(BaseModel):
    content: str


@router.get("/sessions")
async def get_sessions(delegate_id: str | None = None, limit: int = 50):
    return await list_chat_sessions(delegate_id=delegate_id, limit=limit)


@router.post("/sessions")
async def new_session(delegate_id: str):
    session_id = str(uuid.uuid4())
    return await create_chat_session(session_id, delegate_id)


@router.get("/sessions/{session_id}/messages")
async def get_messages(session_id: str, limit: int = 200):
    return await list_chat_messages(session_id, limit=limit)


@router.post("/sessions/{session_id}/messages")
async def send_message(session_id: str, body: ChatMessageIn):
    """Send a user message and get an LLM-generated assistant response."""
    sessions = await list_chat_sessions(limit=500)
    session = next((s for s in sessions if s["id"] == session_id), None)
    if session is None:
        raise HTTPException(status_code=404, detail="Chat session not found")

    delegate_id = session["delegate_id"]

    # Save user message first so it appears in history even if LLM fails.
    user_msg = await add_chat_message(
        msg_id=str(uuid.uuid4()),
        session_id=session_id,
        role="user",
        content=body.content,
    )

    # Assemble LLM input
    try:
        memories = await list_memories()
    except Exception:
        logger.warning("Failed to load memories for chat", exc_info=True)
        memories = []

    try:
        goals = await get_career_goals()
    except Exception:
        logger.warning("Failed to load goals for chat", exc_info=True)
        goals = None

    history = await list_chat_messages(session_id, limit=MAX_HISTORY_TURNS * 2)
    messages: list[dict] = [
        {"role": "system", "content": _system_prompt(delegate_id, memories, goals)}
    ]
    for row in history[-MAX_HISTORY_TURNS * 2 :]:
        role = row.get("role", "user")
        messages.append({"role": role, "content": row.get("content", "")})

    try:
        reply = await llm_chat(messages, tier="cheap", delegate_id=delegate_id)
    except BudgetExceededError as e:
        reply = f"(Delegate budget exceeded — {e}. Adjust the budget in Settings to resume.)"
    except Exception as e:
        logger.exception("LLM chat call failed")
        reply = f"(Assistant unavailable: {type(e).__name__}. Check OpenAI credentials in Settings.)"

    assistant_msg = await add_chat_message(
        msg_id=str(uuid.uuid4()),
        session_id=session_id,
        role="assistant",
        content=reply,
    )

    return {"user_message": user_msg, "assistant_message": assistant_msg}
